/**
 * KC rebuild engine — the closed context taxonomy (SYNERGY_MODEL_V1 §2).
 *
 * Closed unions: adding a context is a deliberate schema change, never an
 * ad-hoc string (design law 3). v1 = 10 contexts: 2 postures, 4 phase/events,
 * 4 states. `home/away` and `formation` are deliberately excluded (SM §2 cut).
 *
 * A TraitContext is what a trait *references* (law 1: every trait must
 * reference one); a ContextSnapshot is what the engine *evaluates it against*
 * each increment.
 */

// ---------------------------------------------------------------------------
// Postures — declared states, never inferred. One active per side per increment.
// ---------------------------------------------------------------------------

export type Posture = 'possession' | 'deep-block';

export const POSTURES: readonly Posture[] = ['possession', 'deep-block'];

// ---------------------------------------------------------------------------
// Phases / events — generated by the engine from the posture matchup.
// ---------------------------------------------------------------------------

/** Resolvable windows (SM §6 "playing a hand"). */
export type WindowKind = 'transition' | 'set-piece';

export const WINDOW_KINDS: readonly WindowKind[] = ['transition', 'set-piece'];

/** Non-window event contexts (goal-event maps the legacy onGoal/onConceded hooks). */
export type EventContextKind = WindowKind | 'goal-event' | 'substitution';

// ---------------------------------------------------------------------------
// States — evaluated per increment, stackable.
// ---------------------------------------------------------------------------

export type Scoreline = 'leading' | 'level' | 'chasing';
export type ClockBand = 'early' | 'mid' | 'late';

/** Streak/fitness state tests are threshold comparisons, not enums. SM §2
 *  names both fitness directions ("above/below thresholds"). */
export interface StreakAtLeast {
  kind: 'streak';
  atLeast: number;
}
export interface FitnessBelow {
  kind: 'fitness';
  below: number; // squad-average threshold (per-player scoping arrives with real squads)
}
export interface FitnessAtLeast {
  kind: 'fitness';
  atLeast: number;
}

// ---------------------------------------------------------------------------
// TraitContext — the closed set of things a trait may reference (law 1).
// ---------------------------------------------------------------------------

export type TraitContext =
  | { kind: 'window'; window: WindowKind }        // fires when resolving that window
  | { kind: 'goal-event'; on: 'scored' | 'conceded'; via?: WindowKind } // fires on the goal event (optionally only via that window)
  | { kind: 'substitution' }                       // active for the rest of the batch after an own substitution
  | { kind: 'posture'; posture: Posture }          // fires while own posture is X
  | { kind: 'scoreline'; is: Scoreline }
  | { kind: 'clock'; band: ClockBand }
  | StreakAtLeast
  | FitnessBelow
  | FitnessAtLeast;

// ---------------------------------------------------------------------------
// ContextSnapshot — the regime a trait is evaluated against, per increment.
// ---------------------------------------------------------------------------

export interface ContextSnapshot {
  /** Own side's active posture this increment (declared, never inferred). */
  posture: Posture;
  scoreline: Scoreline;
  clock: ClockBand;
  streak: number;
  /** Squad-average fitness 0–10 (stub squads default 10). */
  fitness: number;
  /** True from an own substitution until the end of that batch (fresh legs). */
  subThisBatch: boolean;
}

/**
 * Does a *state-like* trait context hold in this snapshot? Window / goal-event
 * contexts are event-scoped — they match at their event site, not here — so
 * they return false from the per-increment state test. Substitution is
 * batch-scoped state: active from the sub until the batch ends.
 */
export function stateContextActive(ctx: TraitContext, snap: ContextSnapshot): boolean {
  switch (ctx.kind) {
    case 'posture':
      return snap.posture === ctx.posture;
    case 'scoreline':
      return snap.scoreline === ctx.is;
    case 'clock':
      return snap.clock === ctx.band;
    case 'streak':
      return snap.streak >= ctx.atLeast;
    case 'fitness':
      return 'below' in ctx ? snap.fitness < ctx.below : snap.fitness >= ctx.atLeast;
    case 'substitution':
      return snap.subThisBatch;
    default:
      return false;
  }
}

/** Scoreline from a side's perspective. */
export function scorelineFor(goalsFor: number, goalsAgainst: number): Scoreline {
  if (goalsFor > goalsAgainst) return 'leading';
  if (goalsFor < goalsAgainst) return 'chasing';
  return 'level';
}
