export * from './calibration-expansion-batch-05-runtime';

import { getV8CalibrationPlayer } from './calibration-cards';
import type { V8Zone } from './core';
import { isV8ChanceType, type V8TacticalCardInstance } from './tactical';
import * as runtime from './calibration-expansion-batch-05-runtime';

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function otherSide(side: runtime.V8CalibrationSide): runtime.V8CalibrationSide {
  return side === 'home' ? 'away' : 'home';
}

function activeWalsh(
  state: runtime.V8CalibrationState,
  side: runtime.V8CalibrationSide,
): runtime.V8CalibrationRuntimePlayer | undefined {
  return Object.values(state.players)
    .filter((player) =>
      player.side === side
      && player.cardId === 'keira-walsh'
      && runtime.isCalibrationActionEnabled(state, player.runtimeId)
      && (state.periodCounters[`walsh-beat-the-press:${player.runtimeId}`] ?? 0) === 0
    )
    .sort((a, b) => a.deployedOrder - b.deployedOrder || a.runtimeId.localeCompare(b.runtimeId))[0];
}

function applyWalshPressReaction(
  state: runtime.V8CalibrationState,
  pressingSide: runtime.V8CalibrationSide,
): runtime.V8CalibrationState {
  const receivingSide = otherSide(pressingSide);
  const walsh = activeWalsh(state, receivingSide);
  if (!walsh) return state;

  let next = clone(state);
  next.periodCounters[`walsh-beat-the-press:${walsh.runtimeId}`] = 1;
  const generated = runtime.addCalibrationTacticalToHand(next, receivingSide, 'through_ball', {
    attModifier: 2,
    generatedBy: 'keira-walsh',
  });
  next = generated.state;
  generated.card.metadata.availableFromPeriod = next.period + 1;
  next.events.push({
    type: 'tactical_generated',
    period: next.period,
    text: `${getV8CalibrationPlayer('keira-walsh').realName} · BEAT THE PRESS exploits the press and generates ${generated.card.name} (+2 ATT).`,
  });
  return next;
}

export function playCalibrationTactical(
  state: runtime.V8CalibrationState,
  side: runtime.V8CalibrationSide,
  cardId: string,
  zone: V8Zone,
  options: { ignoreEnergy?: boolean; window?: boolean } = {},
): runtime.V8CalibrationState {
  const card = runtime.calibrationHandTacticals(state, side).find((candidate) => candidate.id === cardId);
  const reactsToPress = card?.type === 'trigger_press';
  const resolved = runtime.playCalibrationTactical(state, side, cardId, zone, options);
  return reactsToPress ? applyWalshPressReaction(resolved, side) : resolved;
}

export function resolveCommittedCalibrationTactical(
  state: runtime.V8CalibrationState,
  side: runtime.V8CalibrationSide,
  card: V8TacticalCardInstance,
  zone: V8Zone,
  paidCost: number,
): runtime.V8CalibrationState {
  const next = clone(state);
  next.teams[side].hand.push({ kind: 'tactical', card });
  const resolved = playCalibrationTactical(next, side, card.id, zone, { ignoreEnergy: true });
  const latest = [...resolved.tacticalResolutions].reverse()
    .find((resolution) => resolution.side === side && resolution.cardId === card.id);
  if (latest) latest.cost = paidCost;
  return resolved;
}

export interface V8Batch06ResolvedWindowPlay {
  side: runtime.V8CalibrationSide;
  card: V8TacticalCardInstance;
  zone: V8Zone;
  cost: number;
}

/**
 * Batch 05 owns the established window ordering. Trigger Press reactions can be applied after that
 * window resolves because a Tactical generated by BEAT THE PRESS cannot be newly queued into an
 * already-resolving blind window; it remains same-period generated evidence and is banked for the
 * next commitment if unused.
 */
export function resolveGeneratedTacticalWindow(
  state: runtime.V8CalibrationState,
  plays: readonly runtime.V8CalibrationWindowPlay[],
): { state: runtime.V8CalibrationState; plays: V8Batch06ResolvedWindowPlay[] } {
  const pressSides: runtime.V8CalibrationSide[] = [];
  for (const play of plays) {
    const card = runtime.calibrationHandTacticals(state, play.side).find((candidate) => candidate.id === play.cardId);
    if (card?.type === 'trigger_press' && !pressSides.includes(play.side)) pressSides.push(play.side);
  }

  const result = runtime.resolveGeneratedTacticalWindow(state, plays);
  let next = result.state;
  for (const pressingSide of pressSides) next = applyWalshPressReaction(next, pressingSide);
  return { ...result, state: next };
}
