/**
 * KC six-contest engine (NW-141) — the card model + loader.
 *
 * A `KCCard` is the engine `Card` (contests.ts: role/pos/contest/tilt/att/def)
 * plus the shop-facing identity (name/rarity/nickname). Its ACTION is looked up
 * from the catalogue (data/actions.ts) at its rarity tier — so a squad's traits
 * are just its cards' actions. The dataset is generated by
 * scripts/kc_v2_regenerate.ts into public/data/kc_v2_cards.json (the live
 * kc_cards.json is left untouched).
 */

import type { Card, Contest, Position } from './contests';
import type { EngineTrait } from './traits';
import { ROLE_BY_NAME, tiltValue } from './data/roles';
import { actionFor, type Rarity } from './data/actions';

export interface KCCard extends Card {
  id: string;
  name: string;
  rarity: Rarity;
  nickname?: string;
}

/** The raw shape emitted into kc_v2_cards.json. */
export interface KCCardJSON {
  id: string;
  name: string;
  nickname?: string;
  pos: Position;
  role: string;
  contest: Contest;
  tilt: number;
  rarity: Rarity;
  att: number;
  def: number;
  aerial?: boolean;
}

/** A card's action as an EngineTrait (empty if the role has no catalogue entry). */
export function cardTraits(card: KCCard): EngineTrait[] {
  const t = actionFor(card.role, card.rarity);
  return t ? [t] : [];
}

/** All traits for a set of cards (a squad's action bundle). */
export function squadTraits(cards: KCCard[]): EngineTrait[] {
  return cards.flatMap(cardTraits);
}

/** Rehydrate a KCCard from its JSON row, backfilling role-derived fields. */
export function fromJSON(row: KCCardJSON): KCCard {
  const role = ROLE_BY_NAME[row.role];
  return {
    id: row.id,
    name: row.name,
    nickname: row.nickname,
    pos: row.pos,
    role: row.role,
    contest: row.contest ?? role?.contest,
    tilt: row.tilt ?? (role ? tiltValue(role.tilt) : 0),
    att: row.att,
    def: row.def,
    rarity: row.rarity,
    aerial: row.aerial,
  };
}

export function loadCards(rows: KCCardJSON[]): KCCard[] {
  return rows.map(fromJSON);
}
